
name: Lint and Test

on: push


jobs:
  lint:
    uses: tybruno/github-workflow-pylama/.github/workflows/pylama-workflow.yml@main
  test:
    uses: tybruno/github-workflow-pytest/.github/workflows/pytest-workflow.yml@main
