name: Pylint

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Analysing the code with pylint
      run: |
        pylint `ls -R|grep .py$|xargs`
    - name: pylinter
      # You may pin to the exact commit or the version.
      # uses: alexanderdamiani/pylinter@d7a7456437e7c4c7e99585df4fe32010599199a8
      uses: alexanderdamiani/pylinter@v1.3.0
      with:
        # directory to run linting on
        python-root: .
        # flake8 flags
        flake8-flags: .
        # mypy flags
        mypy-flags: .
        # optional exit on isort errors
        fail-on-isort: .
        # requirements filepath for project for mypy to prevent library stub missing errors
        requirements-file: requirements-test.txt
      
